# climate_models/hr.yaml
# High-resolution WRF model configuration.
# Defines variables to use from USask WRF PGW dataset.

_target_: nc2pt.climatedata.ClimateModel
name: hr
info: "High Resolution UBC WRF, Western Canada"
alignment_pipeline: ["temporal_crop", "spatial_crop", "user_defined_transforms", "split_data"]
loader: "ubc_wrf"

climate_variables:
  #- ${internal.hr_uas}
  #- ${internal.hr_vas}
  - ${internal.hr_tas}
  #- ${internal.hr_ps}
  #- ${internal.hr_pr}