# climate_models/hr.yaml
# High-resolution WRF model configuration.
# Defines variables to use from USask WRF PGW dataset.

_target_: nc2pt.climatedata.ClimateModel
name: hr
info: "High Resolution USask WRF, Western Canada"

climate_variables:
  - ${internal.hr_uas}
  - ${internal.hr_vas}
  - ${internal.hr_tas}
  - ${internal.hr_pr}