# climate_models/lr.yaml
# Defines the low-resolution ERA5 model, including metadata and its variables.
# Add or remove variables from `climate_variables` as needed.
# Ensure all referenced variables are injected in `injections.yaml`.

_target_: nc2pt.climatedata.ClimateModel
name: lr
info: "Low resolution ERA5, Western Canada"
alignment_pipeline: ["temporal_crop", "regrid", "spatial_crop", "coarsen", "user_defined_transforms"]
emulation_data: true

# Used to interpolate LR data to HR grid. This is typically a high-res field like T2.
hr_ref:
  _target_: nc2pt.climatedata.ClimateVariable
  name: "hr_ref"
  alternative_names: ["T2"]
  path: ${internal.paths.hr_ref}
  is_west_negative: true
  invariant: true

climate_variables:
  # Activate variables to include in the LR model
  - ${internal.lr_uas}
  #- ${internal.lr_vas}
  #- ${internal.lr_tas}
  #- ${internal.lr_pr}