# Meridional (North-South) component of near-surface wind from ERA 5 (LR Model)

_target_: nc2pt.climatedata.ClimateVariable
name: "vas"
alternative_names: ["V10", "v10", "vas"]
path: ${internal.paths.lr.vas}
apply_standardize: false
apply_normalize: true
invariant: false
coarsening_method: "mean"
transform: []