# Precipitation from WRF (HR model)

_target_: nc2pt.climatedata.ClimateVariable
name: "pr"
alternative_names: ["PREC", "HPRECIPNC"]
path:  ${internal.paths.hr.pr}
apply_standardize: false
apply_normalize: true
invariant: false
transform: []