# Surface pressure from WRF (HR Model)

_target_: nc2pt.climatedata.ClimateVariable
name: "ps"
alternative_names: ["PSFC"]
path:  ${internal.paths.hr.ps}
is_west_negative: true
apply_standardize: false
apply_normalize: true
invariant: false
transform: []