package: _uas

_target_: nc2pt.climatedata.ClimateVariable
name: "uas"
alternative_names: ["U10", "u10", "uas"]
path: ${internal.paths.hr.uas}
is_west_negative: true
apply_standardize: false
apply_normalize: true
invariant: false
transform: []