# Meridional (North-South) component of 10 m wind from WRF (HR Model)

_target_: nc2pt.climatedata.ClimateVariable
name: "vas"
alternative_names: ["V10", "v10", "vas"]
path: ${internal.paths.hr.vas}
is_west_negative: true
apply_standardize: false
apply_normalize: true
invariant: false
transform: []