# Topography used in WRF simulations (HR Model)

_target_: nc2pt.climatedata.ClimateVariable
name: "land_use"
alternative_names: ["LU_INDEX"]
path: ${internal.paths.hr_invariant}
invariant: true
apply_standardize: false
apply_normalize: true
transform: []