# Topography used in WRF simulations (HR Model)

_target_: nc2pt.climatedata.ClimateVariable
name: "surface_roughness"
alternative_names: ["VAR_SSO"]
path: ${internal.paths.hr_invariant}
invariant: true
apply_standardize: false
apply_normalize: true
transform: []