hr:
  path: /home/nannau/jabbar/data/wrf/*.nc
  is_west_negative: true
  output_path: /home/nannau/gom/wrf
lr:
  path: /home/nannau/jabbar/data/era5/*.nc
  is_west_negative: false
  output_path: /home/nannau/gom/era5

vars:
  U10: 
    alternative_names: ["u10", "uas"]
    standardize: true
    standardize_style: "normal"
  V10:
    alternative_names: ["v10", "vas"]
    standardize: true
    standardize_style: "normal"
dims:
  time:
    alternative_names: ["Time", "Times", "times"]
  rlat:
    alternative_names: ["rotated_latitude"]
    hr_only: true
  rlon:
    alternative_names: ["rotated_longitude"]
    hr_only: true
coords:
  lat:
    alternative_names: ["latitude", "Lat", "Latitude"]
  lon:
    alternative_names: ["longitude", "Long", "Lon", "Longitude"]
time:
  full: 
    start: "20001001T01:00:00"
    # end: "20001002T01:00:00"
    end: "20150929T23:00:00"
  test_years: [2000, 2009, 2014]
  train_years: [2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2010, 2011, 2012, 2013, 2015]

spatial:
  scale_factor: 8
  x: 
    first_index: 0
    last_index: 632
  y:
    first_index: 2
    last_index: 634

engine: h5netcdf

compute:
  threads_per_worker: 2
  memory_limit: "24GB"
